"""empty message

Revision ID: 15c42909fe74
Revises: 86f7e5122957
Create Date: 2024-05-16 16:40:03.163831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c42909fe74'
down_revision = '86f7e5122957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hability_1', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('role_hablity_1_key', type_='unique')
        batch_op.create_unique_constraint(None, ['hability_1'])
        batch_op.drop_column('hablity_1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hablity_1', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('role_hablity_1_key', ['hablity_1'])
        batch_op.drop_column('hability_1')

    # ### end Alembic commands ###
