"""empty message

Revision ID: 6cfc46be0eae
Revises: 5867e95aed6c
Create Date: 2024-05-24 01:35:00.473900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cfc46be0eae'
down_revision = '5867e95aed6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('difficulty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('difficulty_difficulty_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('difficulty_name')

    with op.batch_alter_table('rarity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('rarity_rarity_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('rarity_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rarity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rarity_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('rarity_rarity_name_key', ['rarity_name'])
        batch_op.drop_column('name')

    with op.batch_alter_table('difficulty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('difficulty_difficulty_name_key', ['difficulty_name'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###
