"""empty message

Revision ID: 86f7e5122957
Revises: a68cc054f51b
Create Date: 2024-05-16 16:23:07.169732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f7e5122957'
down_revision = 'a68cc054f51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('passive', sa.String(length=120), nullable=False),
    sa.Column('hablity_1', sa.String(length=120), nullable=False),
    sa.Column('hability_2', sa.String(length=120), nullable=False),
    sa.Column('hability_3', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hability_2'),
    sa.UniqueConstraint('hability_3'),
    sa.UniqueConstraint('hablity_1'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('passive')
    )
    op.drop_table('clas')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_role', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'role', ['user_role'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_role')

    op.create_table('clas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('passive', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('hablity_1', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('hability_2', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('hability_3', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='clas_pkey'),
    sa.UniqueConstraint('hability_2', name='clas_hability_2_key'),
    sa.UniqueConstraint('hability_3', name='clas_hability_3_key'),
    sa.UniqueConstraint('hablity_1', name='clas_hablity_1_key'),
    sa.UniqueConstraint('name', name='clas_name_key'),
    sa.UniqueConstraint('passive', name='clas_passive_key')
    )
    op.drop_table('role')
    # ### end Alembic commands ###
