"""empty message

Revision ID: a68cc054f51b
Revises: e28100e295b3
Create Date: 2024-05-16 16:10:43.271723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68cc054f51b'
down_revision = 'e28100e295b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_user_class_fkey', type_='foreignkey')
        batch_op.drop_column('user_class')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_class', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_user_class_fkey', 'clas', ['user_class'], ['id'])

    # ### end Alembic commands ###
