"""empty message

Revision ID: beec27288c60
Revises: 311478e53bed
Create Date: 2024-05-16 17:26:02.226108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beec27288c60'
down_revision = '311478e53bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.drop_constraint('reward_label_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.create_unique_constraint('reward_label_key', ['label'])

    # ### end Alembic commands ###
