"""empty message

Revision ID: c6ed6d49bec7
Revises: 6cfc46be0eae
Create Date: 2024-05-24 18:38:14.124594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ed6d49bec7'
down_revision = '6cfc46be0eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.add_column(sa.Column('done', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.drop_column('done')

    # ### end Alembic commands ###
